name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (build stage)
        run: docker build -t practice-4-build --target build .

      - name: Run unit tests
        run: docker run --rm practice-4-build go test ./cmd/lb -v

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Run docker-compose
        run: docker compose up --build --abort-on-container-exit

      - name: Show logs (optional)
        if: always()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down --volumes --remove-orphans
